### ISSUE TITLE
球头像大图

### ISSUE THREAD

**Issue by lolisa** [yinian1992/celery-docs-cn#2]
这里是魔理沙综合征晚期患者一名

**Comment by yinian1992** [comment]
头回见有人开 issue 要头像的，你要冒充我吗DAZE？！

**Comment by lolisa** [comment]
噗，我才是帅气可爱的魔理沙

**Comment by yinian1992** [comment]
大图见 [http://konachan.com/post/show/97880](http://konachan.com/post/show/97880)。

**Comment by lolisa** [comment]
Thx DAZE
